import { Technique } from './types';

export const localizedTechniques: { [key: string]: Technique[] } = {
  en: [
    {
      id: 'vedic_astrology',
      name: 'Vedic Astrology',
      description: 'Ancient Indian system of astrology to understand planetary influences on your life.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'Numerology',
      description: 'Explore the mystical relationship between numbers and life events based on your birth date.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'Tarot Reading',
      description: 'Algorithmic Tarot-style prediction for insights into your past, present, and future.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'Palmistry',
      description: 'Upload a photo of your palm to receive a personalized reading of your life lines and mounts.',
      enabled: true,
    },
  ],
  hi: [
    {
      id: 'vedic_astrology',
      name: 'वैदिक ज्योतिष',
      description: 'आपके जीवन पर ग्रहों के प्रभाव को समझने के लिए ज्योतिष की प्राचीन भारतीय प्रणाली।',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'अंक ज्योतिष',
      description: 'अपनी जन्मतिथि के आधार पर संख्याओं और जीवन की घटनाओं के बीच रहस्यमय संबंध का अन्वेषण करें।',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'टैरो रीडिंग',
      description: 'आपके अतीत, वर्तमान और भविष्य के बारे में जानकारी के लिए एल्गोरिथम टैरो-शैली की भविष्यवाणी।',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'हस्तरेखा शास्त्र',
      description: 'अपने जीवन रेखाओं और पर्वतों का व्यक्तिगत पठन प्राप्त करने के लिए अपनी हथेली का एक फोटो अपलोड करें।',
      enabled: true,
    },
  ],
  es: [
    {
      id: 'vedic_astrology',
      name: 'Astrología Védica',
      description: 'Antiguo sistema indio de astrología para comprender las influencias planetarias en tu vida.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'Numerología',
      description: 'Explora la relación mística entre los números y los eventos de la vida según tu fecha de nacimiento.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'Lectura de Tarot',
      description: 'Predicción algorítmica estilo Tarot para obtener información sobre tu pasado, presente y futuro.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'Quiromancia',
      description: 'Sube una foto de tu palma para recibir una lectura personalizada de las líneas y montes de tu vida.',
      enabled: true,
    },
  ],
  fr: [
    {
      id: 'vedic_astrology',
      name: 'Astrologie Védique',
      description: 'Ancien système indien d\'astrologie pour comprendre les influences planétaires sur votre vie.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'Numérologie',
      description: 'Explorez la relation mystique entre les nombres et les événements de la vie en fonction de votre date de naissance.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'Lecture de Tarot',
      description: 'Prédiction algorithmique de style Tarot pour des aperçus de votre passé, présent et futur.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'Chiromancie',
      description: 'Téléchargez une photo de votre paume pour recevoir une lecture personnalisée de vos lignes de vie et de vos monts.',
      enabled: true,
    },
  ],
  mr: [
    {
      id: 'vedic_astrology',
      name: 'वैदिक ज्योतिष',
      description: 'तुमच्या जीवनातील ग्रहांच्या प्रभावांना समजून घेण्यासाठी प्राचीन भारतीय ज्योतिष प्रणाली.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'अंकशास्त्र',
      description: 'तुमच्या जन्मतारखेनुसार अंक आणि जीवन घटनांमधील गूढ संबंधांचा शोध घ्या.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'टॅरो रीडिंग',
      description: 'तुमच्या भूतकाळ, वर्तमान आणि भविष्याबद्दल माहितीसाठी अल्गोरिदमिक टॅरो-शैलीचे भाकीत.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'हस्तरेखाशास्त्र',
      description: 'तुमच्या जीवन रेषा आणि पर्वतांचे वैयक्तिकृत वाचन मिळवण्यासाठी तुमच्या तळहाताचा फोटो अपलोड करा.',
      enabled: true,
    },
  ],
  ta: [
    {
      id: 'vedic_astrology',
      name: 'வேத ஜோதிடம்',
      description: 'உங்கள் வாழ்க்கையில் கிரகங்களின் தாக்கங்களைப் புரிந்துகொள்ள பண்டைய இந்திய ஜோதிட அமைப்பு.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'எண் கணிதம்',
      description: 'உங்கள் பிறந்த தேதியின் அடிப்படையில் எண்கள் மற்றும் வாழ்க்கை நிகழ்வுகளுக்கு இடையிலான மர்மமான உறவை ஆராயுங்கள்.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'டாரோட் வாசிப்பு',
      description: 'உங்கள் கடந்தகாலம், நிகழ்காலம் மற்றும் எதிர்காலம் பற்றிய நுண்ணறிவுகளுக்கான அல்காரிதம் டாரோட் பாணி கணிப்பு.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'கைரேகை சாஸ்திரம்',
      description: 'உங்கள் வாழ்க்கை கோடுகள் மற்றும் மேடுகளின் தனிப்பயனாக்கப்பட்ட வாசிப்பைப் பெற உங்கள் உள்ளங்கையின் புகைப்படத்தைப் பதிவேற்றவும்.',
      enabled: true,
    },
  ],
  te: [
    {
      id: 'vedic_astrology',
      name: 'వేద జ్యోతిష్యం',
      description: 'మీ జీవితంపై గ్రహాల ప్రభావాలను అర్థం చేసుకోవడానికి ప్రాచీన భారతీయ జ్యోతిష్య వ్యవస్థ.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'సంఖ్యాశాస్త్రం',
      description: 'మీ పుట్టిన తేదీ ఆధారంగా సంఖ్యలు మరియు జీవిత సంఘటనల మధ్య ఆధ్యాత్మిక సంబంధాన్ని అన్వేషించండి.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'టారోట్ పఠనం',
      description: 'మీ గతం, వర్తమానం మరియు భవిష్యత్తుపై అంతర్దృష్టుల కోసం అల్గారిథమిక్ టారో-శైలి అంచనా.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'హస్తసాముద్రికం',
      description: 'మీ జీవిత రేఖలు మరియు పర్వతాల వ్యక్తిగతీకరించిన పఠనాన్ని స్వీకరించడానికి మీ అరచేతి ఫోటోను అప్‌లోడ్ చేయండి.',
      enabled: true,
    },
  ],
  bn: [
    {
      id: 'vedic_astrology',
      name: 'বৈদিক জ্যোতিষ',
      description: 'আপনার জীবনে গ্রহের প্রভাব বোঝার জন্য প্রাচীন ভারতীয় জ্যোতিষ ব্যবস্থা।',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'সংখ্যাতত্ত্ব',
      description: 'আপনার জন্ম তারিখের উপর ভিত্তি করে সংখ্যা এবং জীবনের ঘটনাগুলির মধ্যে রহস্যময় সম্পর্ক অন্বেষণ করুন।',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'ট্যারোট রিডিং',
      description: 'আপনার অতীত, বর্তমান এবং ভবিষ্যত সম্পর্কে অন্তর্দৃষ্টির জন্য অ্যালগরিদমিক ট্যারোট-স্টাইলের পূর্বাভাস।',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'হস্তরেখাবিদ্যা',
      description: 'আপনার জীবন রেখা এবং মাউন্টগুলির একটি ব্যক্তিগতকৃত পাঠ পেতে আপনার করতল এর একটি ছবি আপলোড করুন।',
      enabled: true,
    },
  ],
  gu: [
    {
      id: 'vedic_astrology',
      name: 'વૈદિક જ્યોતિષ',
      description: 'તમારા જીવન પર ગ્રહોના પ્રભાવને સમજવા માટે પ્રાચીન ભારતીય જ્યોતિષ પ્રણાલી.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'અંકશાસ્ત્ર',
      description: 'તમારી જન્મતારીખના આધારે સંખ્યાઓ અને જીવનની ઘટનાઓ વચ્ચેના રહસ્યમય સંબંધનું અન્વેષણ કરો.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'ટેરોટ રીડિંગ',
      description: 'તમારા ભૂતકાળ, વર્તમાન અને ભવિષ્યમાં આંતરદૃષ્ટિ માટે અલ્ગોરિધમિક ટેરો-શૈલીની આગાહી.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'હસ્તરેખાશાસ્ત્ર',
      description: 'તમારા જીવન રેખાઓ અને માઉન્ટ્સનું વ્યક્તિગત વાંચન મેળવવા માટે તમારા હથેળીનો ફોટો અપલોડ કરો.',
      enabled: true,
    },
  ],
  kn: [
    {
      id: 'vedic_astrology',
      name: 'ವೈದಿಕ ಜ್ಯೋತಿಷ್ಯ',
      description: 'ನಿಮ್ಮ ಜೀವನದ ಮೇಲೆ ಗ್ರಹಗಳ ಪ್ರಭಾವಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಪ್ರಾಚೀನ ಭಾರತೀಯ ಜ್ಯೋತಿಷ್ಯ ವ್ಯವಸ್ಥೆ.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'ಸಂಖ್ಯಾಶಾಸ್ತ್ರ',
      description: 'ನಿಮ್ಮ ಜನ್ಮ ದಿನಾಂಕದ ಆಧಾರದ ಮೇಲೆ ಸಂಖ್ಯೆಗಳು ಮತ್ತು ಜೀವನ ಘಟನೆಗಳ ನಡುವಿನ ಅತೀಂದ್ರಿಯ ಸಂಬಂಧವನ್ನು ಅನ್ವೇಷಿಸಿ.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'ಟ್ಯಾರೋ ಓದುವಿಕೆ',
      description: 'ನಿಮ್ಮ ಭೂತ, ವರ್ತಮಾನ ಮತ್ತು ಭವಿಷ್ಯದ ಬಗ್ಗೆ ಒಳನೋಟಗಳಿಗಾಗಿ ಅಲ್ಗಾರಿದಮಿಕ್ ಟ್ಯಾರೋ-ಶೈಲಿಯ ಭವಿಷ್ಯ.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'ಹಸ್ತಸಾಮುದ್ರಿಕ ಶಾಸ್ತ್ರ',
      description: 'ನಿಮ್ಮ ಜೀವನ ರೇಖೆಗಳು ಮತ್ತು ಪರ್ವತಗಳ ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಓದುವಿಕೆಯನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಅಂಗೈಯ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
      enabled: true,
    },
  ],
  ml: [
    {
      id: 'vedic_astrology',
      name: 'വേദ ജ്യോതിഷം',
      description: 'നിങ്ങളുടെ ജീവിതത്തിൽ ഗ്രഹങ്ങളുടെ സ്വാധീനം മനസ്സിലാക്കുന്നതിനുള്ള പുരാതന ഇന്ത്യൻ ജ്യോതിഷ സമ്പ്രദായം.',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'സംഖ്യാശാസ്ത്രം',
      description: 'നിങ്ങളുടെ ജനനത്തീയതി അടിസ്ഥാനമാക്കി സംഖ്യകളും ജീവിത സംഭവങ്ങളും തമ്മിലുള്ള നിഗൂഢമായ ബന്ധം പര്യവേക്ഷണം ചെയ്യുക.',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'ടാരോട്ട് വായന',
      description: 'നിങ്ങളുടെ ഭൂതകാലം, വർത്തമാനം, ഭാവി എന്നിവയെക്കുറിച്ചുള്ള ഉൾക്കാഴ്ചകൾക്കായി അൽഗോരിതം ടാരോട്ട് ശൈലിയിലുള്ള പ്രവചനം.',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'ഹസ്തരേഖാശാസ്ത്രം',
      description: 'നിങ്ങളുടെ ജീവിതരേഖകളുടെയും മൗണ്ടുകളുടെയും വ്യക്തിഗത വായന ലഭിക്കുന്നതിന് നിങ്ങളുടെ കൈപ്പത്തിയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.',
      enabled: true,
    },
  ],
  or: [
    {
      id: 'vedic_astrology',
      name: 'ବୈଦିକ ଜ୍ୟୋତିଷ',
      description: 'ଆପଣଙ୍କ ଜୀବନ ଉପରେ ଗ୍ରହମାନଙ୍କର ପ୍ରଭାବକୁ ବୁଝିବା ପାଇଁ ପ୍ରାଚୀନ ଭାରତୀୟ ଜ୍ୟୋତିଷ ପ୍ରଣାଳୀ |',
      enabled: true,
    },
    {
      id: 'numerology',
      name: 'ସଂଖ୍ୟା ଜ୍ୟୋତିଷ',
      description: 'ଆପଣଙ୍କର ଜନ୍ମ ତାରିଖ ଉପରେ ଆଧାର କରି ସଂଖ୍ୟା ଏବଂ ଜୀବନର ଘଟଣାଗୁଡ଼ିକ ମଧ୍ୟରେ ରହସ୍ୟମୟ ସମ୍ପର୍କକୁ ଅନୁସନ୍ଧାନ କରନ୍ତୁ |',
      enabled: true,
    },
    {
      id: 'tarot',
      name: 'ଟାରୋଟ୍ ପଠନ',
      description: 'ଆପଣଙ୍କର ଅତୀତ, ବର୍ତ୍ତମାନ, ଏବଂ ଭବିଷ୍ୟତ ବିଷୟରେ ଜ୍ଞାନ ପାଇଁ ଆଲଗୋରିଦମିକ୍ ଟାରୋ-ଶୈଳୀର ଭବିଷ୍ୟବାଣୀ |',
      enabled: true,
    },
    {
      id: 'palmistry',
      name: 'ହସ୍ତରେଖା ବିଜ୍ଞାନ',
      description: 'ଆପଣଙ୍କ ଜୀବନ ରେଖା ଏବଂ ମାଉଣ୍ଟଗୁଡ଼ିକର ଏକ ବ୍ୟକ୍ତିଗତ ପଠନ ପ୍ରାପ୍ତ କରିବାକୁ ଆପଣଙ୍କ ହାତର ଏକ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ |',
      enabled: true,
    },
  ],
};


export const translations: { [key: string]: any } = {
    en: {
        choosePathTitle: "Choose Your Path to Insight",
        choosePathSubtitle: "Select a method to begin your journey of discovery.",
        formTitle: "Enter Your Details",
        formSubtitle: (techniqueName: string) => `Provide your information for an accurate ${techniqueName} reading.`,
        formNameLabel: "Full Name",
        formDobLabel: "Date of Birth",
        formTobLabel: "Time of Birth",
        formPobLabel: "Place of Birth (City, Country)",
        formButton: "Begin Conversation",
        disclaimerTitle: "Astrological Foundation",
        disclaimerBody: "The Vibe Oracle utilizes an AI model extensively trained on established astrological principles and ancient texts. Our system interprets planetary positions and cosmic alignments to provide insights based on your unique data.",
        disclaimerButton: "Begin My Reading",
        palmistryTitle: "Provide Your Palm Photo",
        palmistrySubtitle: "Upload a clear photo of your dominant hand for analysis.",
        palmistryPreview: "Your palm image will appear here.",
        palmistryInstructionsTitle: "Instructions for a Clear Photo:",
        palmistryInstruction1: "Use your dominant hand (the one you write with).",
        palmistryInstruction2: "Ensure good, even lighting. Avoid strong shadows.",
        palmistryInstruction3: "Keep your palm flat and fingers slightly apart.",
        palmistryInstruction4: "Make sure your entire palm is visible in the frame.",
        palmistryUploadButton: "Upload Photo from Device",
        palmistryRetakeButton: "Retake",
        palmistryAnalyzeButton: "Analyze Palm",
        palmistryAnalyzingText: "Analyzing the lines of fate...",
        consentTitle: "Palmistry Analysis Consent",
        consentBody1: "To provide a palm reading, we need to analyze a photo of your hand.",
        consentBody2: "Your Privacy is Important:",
        consentLi1: "Your photo is used solely for generating this one-time reading.",
        consentLi2: "The image is processed and will not be stored on our servers after the session.",
        consentLi3: "We will never use your photo for any other purpose or share it with third parties.",
        consentBody3: "By proceeding, you consent to the temporary upload and analysis of your palm photo for a personalized palmistry reading.",
        consentDecline: "Decline",
        consentAccept: "Accept and Proceed",
        footerText: "Powered by advanced astrological models. All predictions are based on established astrological principles.",
    },
    hi: {
        choosePathTitle: "अंतर्दृष्टि के लिए अपना मार्ग चुनें",
        choosePathSubtitle: "खोज की अपनी यात्रा शुरू करने के लिए एक विधि चुनें।",
        formTitle: "अपना विवरण दर्ज करें",
        formSubtitle: (techniqueName: string) => `एक सटीक ${techniqueName} पढ़ने के लिए अपनी जानकारी प्रदान करें।`,
        formNameLabel: "पूरा नाम",
        formDobLabel: "जन्म तिथि",
        formTobLabel: "जन्म का समय",
        formPobLabel: "जन्म स्थान (शहर, देश)",
        formButton: "बातचीत शुरू करें",
        disclaimerTitle: "ज्योतिषीय आधार",
        disclaimerBody: "वाइब ओरेकल स्थापित ज्योतिषीय सिद्धांतों और प्राचीन ग्रंथों पर बड़े पैमाने पर प्रशिक्षित एआई मॉडल का उपयोग करता है। हमारी प्रणाली आपके अद्वितीय डेटा के आधार पर अंतर्दृष्टि प्रदान करने के लिए ग्रहों की स्थिति और ब्रह्मांडीय संरेखण की व्याख्या करती है।",
        disclaimerButton: "मेरा पढ़ना शुरू करें",
        palmistryTitle: "अपनी हथेली का फोटो प्रदान करें",
        palmistrySubtitle: "विश्लेषण के लिए अपने प्रमुख हाथ का एक स्पष्ट फोटो अपलोड करें।",
        palmistryPreview: "आपकी हथेली की छवि यहां दिखाई देगी।",
        palmistryInstructionsTitle: "एक स्पष्ट फोटो के लिए निर्देश:",
        palmistryInstruction1: "अपने प्रमुख हाथ का प्रयोग करें (जिससे आप लिखते हैं)।",
        palmistryInstruction2: "अच्छी, समान रोशनी सुनिश्चित करें। तेज छाया से बचें।",
        palmistryInstruction3: "अपनी हथेली को सपाट रखें और उंगलियों को थोड़ा अलग रखें।",
        palmistryInstruction4: "सुनिश्चित करें कि आपकी पूरी हथेली फ्रेम में दिखाई दे रही है।",
        palmistryUploadButton: "डिवाइस से फोटो अपलोड करें",
        palmistryRetakeButton: "फिर से लें",
        palmistryAnalyzeButton: "हथेली का विश्लेषण करें",
        palmistryAnalyzingText: "भाग्य की रेखाओं का विश्लेषण किया जा रहा है...",
        consentTitle: "हस्तरेखा विश्लेषण सहमति",
        consentBody1: "हस्तरेखा पढ़ने के लिए, हमें आपके हाथ की एक तस्वीर का विश्लेषण करने की आवश्यकता है।",
        consentBody2: "आपकी गोपनीयता महत्वपूर्ण है:",
        consentLi1: "आपकी तस्वीर का उपयोग केवल इस एक बार के पढ़ने के लिए किया जाता है।",
        consentLi2: "छवि को संसाधित किया जाता है और सत्र के बाद हमारे सर्वर पर संग्रहीत नहीं किया जाएगा।",
        consentLi3: "हम आपकी तस्वीर का उपयोग कभी भी किसी अन्य उद्देश्य के लिए नहीं करेंगे या इसे तीसरे पक्ष के साथ साझा नहीं करेंगे।",
        consentBody3: "आगे बढ़कर, आप एक व्यक्तिगत हस्तरेखा पढ़ने के लिए अपनी हथेली की तस्वीर के अस्थायी अपलोड और विश्लेषण के लिए सहमति देते हैं।",
        consentDecline: "अस्वीकार करें",
        consentAccept: "स्वीकार करें और आगे बढ़ें",
        footerText: "उन्नत ज्योतिषीय मॉडलों द्वारा संचालित। सभी भविष्यवाणियां स्थापित ज्योतिषीय सिद्धांतों पर आधारित हैं।",
    },
    es: {
        choosePathTitle: "Elige tu Camino hacia la Perspicacia",
        choosePathSubtitle: "Selecciona un método para comenzar tu viaje de descubrimiento.",
        formTitle: "Introduce tus Datos",
        formSubtitle: (techniqueName: string) => `Proporciona tu información para una lectura precisa de ${techniqueName}.`,
        formNameLabel: "Nombre Completo",
        formDobLabel: "Fecha de Nacimiento",
        formTobLabel: "Hora de Nacimiento",
        formPobLabel: "Lugar de Nacimiento (Ciudad, País)",
        formButton: "Comenzar Conversación",
        disclaimerTitle: "Fundamento Astrológico",
        disclaimerBody: "El Oráculo Vibe utiliza un modelo de IA entrenado extensivamente en principios astrológicos establecidos y textos antiguos. Nuestro sistema interpreta las posiciones planetarias y alineaciones cósmicas para proporcionar ideas basadas en tus datos únicos.",
        disclaimerButton: "Comenzar mi Lectura",
        palmistryTitle: "Proporciona la Foto de tu Palma",
        palmistrySubtitle: "Sube una foto clara de tu mano dominante para el análisis.",
        palmistryPreview: "La imagen de tu palma aparecerá aquí.",
        palmistryInstructionsTitle: "Instrucciones para una Foto Clara:",
        palmistryInstruction1: "Usa tu mano dominante (con la que escribes).",
        palmistryInstruction2: "Asegura una iluminación buena y uniforme. Evita sombras fuertes.",
        palmistryInstruction3: "Mantén tu palma plana y los dedos ligeramente separados.",
        palmistryInstruction4: "Asegúrate de que toda tu palma sea visible en el encuadre.",
        palmistryUploadButton: "Subir Foto desde el Dispositivo",
        palmistryRetakeButton: "Tomar de Nuevo",
        palmistryAnalyzeButton: "Analizar Palma",
        palmistryAnalyzingText: "Analizando las líneas del destino...",
        consentTitle: "Consentimiento para Análisis de Quiromancia",
        consentBody1: "Para proporcionar una lectura de la palma, necesitamos analizar una foto de tu mano.",
        consentBody2: "Tu Privacidad es Importante:",
        consentLi1: "Tu foto se usa únicamente para generar esta lectura única.",
        consentLi2: "La imagen se procesa y no se almacenará en nuestros servidores después de la sesión.",
        consentLi3: "Nunca usaremos tu foto para ningún otro propósito ni la compartiremos con terceros.",
        consentBody3: "Al continuar, das tu consentimiento para la carga y el análisis temporal de la foto de tu palma para una lectura de quiromancia personalizada.",
        consentDecline: "Rechazar",
        consentAccept: "Aceptar y Continuar",
        footerText: "Impulsado por modelos astrológicos avanzados. Todas las predicciones se basan en principios astrológicos establecidos.",
    },
    fr: {
        choosePathTitle: "Choisissez Votre Chemin vers la Connaissance",
        choosePathSubtitle: "Sélectionnez une méthode pour commencer votre voyage de découverte.",
        formTitle: "Entrez vos Coordonnées",
        formSubtitle: (techniqueName: string) => `Fournissez vos informations pour une lecture précise de ${techniqueName}.`,
        formNameLabel: "Nom Complet",
        formDobLabel: "Date de Naissance",
        formTobLabel: "Heure de Naissance",
        formPobLabel: "Lieu de Naissance (Ville, Pays)",
        formButton: "Commencer la Conversation",
        disclaimerTitle: "Fondement Astrologique",
        disclaimerBody: "L'Oracle Vibe utilise un modèle d'IA entraîné de manière approfondie sur des principes astrologiques établis et des textes anciens. Notre système interprète les positions planétaires et les alignements cosmiques pour fournir des informations basées sur vos données uniques.",
        disclaimerButton: "Commencer ma Lecture",
        palmistryTitle: "Fournissez la Photo de votre Paume",
        palmistrySubtitle: "Téléchargez une photo claire de votre main dominante pour analyse.",
        palmistryPreview: "L'image de votre paume apparaîtra ici.",
        palmistryInstructionsTitle: "Instructions pour une Photo Claire :",
        palmistryInstruction1: "Utilisez votre main dominante (celle avec laquelle vous écrivez).",
        palmistryInstruction2: "Assurez un bon éclairage uniforme. Évitez les ombres fortes.",
        palmistryInstruction3: "Gardez votre paume à plat et les doigts légèrement écartés.",
        palmistryInstruction4: "Assurez-vous que toute votre paume est visible dans le cadre.",
        palmistryUploadButton: "Télécharger une Photo",
        palmistryRetakeButton: "Reprendre",
        palmistryAnalyzeButton: "Analyser la Paume",
        palmistryAnalyzingText: "Analyse des lignes du destin...",
        consentTitle: "Consentement pour l'Analyse de Chiromancie",
        consentBody1: "Pour fournir une lecture de la paume, nous devons analyser une photo de votre main.",
        consentBody2: "Votre Vie Privée est Importante :",
        consentLi1: "Votre photo est utilisée uniquement pour générer cette lecture unique.",
        consentLi2: "L'image est traitée et ne sera pas stockée sur nos serveurs après la session.",
        consentLi3: "Nous n'utiliserons jamais votre photo à d'autres fins et ne la partagerons pas avec des tiers.",
        consentBody3: "En continuant, vous consentez au téléchargement et à l'analyse temporaires de la photo de votre paume pour une lecture de chiromancie personnalisée.",
        consentDecline: "Refuser",
        consentAccept: "Accepter et Continuer",
        footerText: "Propulsé par des modèles astrologiques avancés. Toutes les prédictions sont basées sur des principes astrologiques établis.",
    },
    mr: {
        choosePathTitle: "तुमचा ज्ञानाचा मार्ग निवडा",
        choosePathSubtitle: "तुमचा शोधाचा प्रवास सुरू करण्यासाठी एक पद्धत निवडा.",
        formTitle: "तुमचे तपशील प्रविष्ट करा",
        formSubtitle: (techniqueName: string) => `अचूक ${techniqueName} वाचनासाठी तुमची माहिती द्या.`,
        formNameLabel: "पूर्ण नाव",
        formDobLabel: "जन्मतारीख",
        formTobLabel: "जन्मवेळ",
        formPobLabel: "जन्मस्थान (शहर, देश)",
        formButton: "संभाषण सुरू करा",
        disclaimerTitle: "ज्योतिषीय आधार",
        disclaimerBody: "व्हायब ओरेकल स्थापित ज्योतिषीय तत्त्वे आणि प्राचीन ग्रंथांवर विस्तृतपणे प्रशिक्षित AI मॉडेलचा वापर करते. आमची प्रणाली तुमच्या अद्वितीय डेटावर आधारित अंतर्दृष्टी प्रदान करण्यासाठी ग्रहांची स्थिती आणि वैश्विक संरेखनांचा अर्थ लावते.",
        disclaimerButton: "माझे वाचन सुरू करा",
        palmistryTitle: "तुमच्या तळहाताचा फोटो द्या",
        palmistrySubtitle: "विश्लेषणासाठी तुमच्या प्रमुख हाताचा स्पष्ट फोटो अपलोड करा.",
        palmistryPreview: "तुमच्या तळहाताची प्रतिमा येथे दिसेल.",
        palmistryInstructionsTitle: "स्पष्ट फोटोसाठी सूचना:",
        palmistryInstruction1: "तुमचा प्रमुख हात वापरा (ज्याने तुम्ही लिहिता).",
        palmistryInstruction2: "चांगला, समान प्रकाश असल्याची खात्री करा. तीव्र सावल्या टाळा.",
        palmistryInstruction3: "तुमचा तळहात सपाट ठेवा आणि बोटे किंचित वेगळी ठेवा.",
        palmistryInstruction4: "तुमचा संपूर्ण तळहात फ्रेममध्ये दिसत असल्याची खात्री करा.",
        palmistryUploadButton: "डिव्हाइसवरून फोटो अपलोड करा",
        palmistryRetakeButton: "पुन्हा घ्या",
        palmistryAnalyzeButton: "तळहाताचे विश्लेषण करा",
        palmistryAnalyzingText: "भाग्याच्या रेषांचे विश्लेषण करत आहे...",
        consentTitle: "हस्तरेखा विश्लेषण संमती",
        consentBody1: "हस्तरेखा वाचन प्रदान करण्यासाठी, आम्हाला तुमच्या हाताच्या फोटोचे विश्लेषण करणे आवश्यक आहे.",
        consentBody2: "तुमची गोपनीयता महत्त्वाची आहे:",
        consentLi1: "तुमचा फोटो केवळ हे एक-वेळचे वाचन तयार करण्यासाठी वापरला जातो.",
        consentLi2: "प्रतिमेवर प्रक्रिया केली जाते आणि सत्रानंतर आमच्या सर्व्हरवर संग्रहित केली जाणार नाही.",
        consentLi3: "आम्ही तुमचा फोटो कधीही इतर कोणत्याही कारणासाठी वापरणार नाही किंवा तृतीय पक्षांसोबत शेअर करणार नाही.",
        consentBody3: "पुढे जाऊन, तुम्ही वैयक्तिकृत हस्तरेखा वाचनासाठी तुमच्या तळहाताच्या फोटोच्या तात्पुरत्या अपलोड आणि विश्लेषणास संमती देता.",
        consentDecline: "नकार द्या",
        consentAccept: "स्वीकारा आणि पुढे जा",
        footerText: "प्रगत ज्योतिषीय मॉडेल्सद्वारे समर्थित. सर्व भाकिते स्थापित ज्योतिषीय तत्त्वांवर आधारित आहेत.",
    },
    ta: {
        choosePathTitle: "நுண்ணறிவுக்கான உங்கள் பாதையைத் தேர்ந்தெடுக்கவும்",
        choosePathSubtitle: "உங்கள் கண்டுபிடிப்பு பயணத்தைத் தொடங்க ஒரு முறையைத் தேர்ந்தெடுக்கவும்.",
        formTitle: "உங்கள் விவரங்களை உள்ளிடவும்",
        formSubtitle: (techniqueName: string) => `ஒரு துல்லியமான ${techniqueName} வாசிப்பிற்கு உங்கள் தகவலை வழங்கவும்.`,
        formNameLabel: "முழு பெயர்",
        formDobLabel: "பிறந்த தேதி",
        formTobLabel: "பிறந்த நேரம்",
        formPobLabel: "பிறந்த இடம் (நகரம், நாடு)",
        formButton: "உரையாடலைத் தொடங்குங்கள்",
        disclaimerTitle: "ஜோதிட அடித்தளம்",
        disclaimerBody: "வைப் ஆரக்கிள் நிறுவப்பட்ட ஜோதிடக் கொள்கைகள் மற்றும் பண்டைய நூல்களில் விரிவாகப் பயிற்றுவிக்கப்பட்ட ஒரு AI மாதிரியைப் பயன்படுத்துகிறது. எங்கள் அமைப்பு உங்கள் தனித்துவமான தரவின் அடிப்படையில் நுண்ணறிவுகளை வழங்க கிரக நிலைகள் மற்றும் அண்ட சீரமைப்புகளை விளக்குகிறது.",
        disclaimerButton: "என் வாசிப்பைத் தொடங்குங்கள்",
        palmistryTitle: "உங்கள் உள்ளங்கைப் புகைப்படத்தை வழங்கவும்",
        palmistrySubtitle: "பகுப்பாய்விற்காக உங்கள் ஆதிக்கக் கையின் தெளிவான புகைப்படத்தைப் பதிவேற்றவும்.",
        palmistryPreview: "உங்கள் உள்ளங்கை படம் இங்கே தோன்றும்.",
        palmistryInstructionsTitle: "தெளிவான புகைப்படத்திற்கான வழிமுறைகள்:",
        palmistryInstruction1: "உங்கள் ஆதிக்கக் கையைப் பயன்படுத்தவும் (நீங்கள் எழுதும் கை).",
        palmistryInstruction2: "நல்ல, சமமான வெளிச்சத்தை உறுதி செய்யுங்கள். வலுவான நிழல்களைத் தவிர்க்கவும்.",
        palmistryInstruction3: "உங்கள் உள்ளங்கையைத் தட்டையாகவும், விரல்களைச் சற்று விலக்கியும் வைக்கவும்.",
        palmistryInstruction4: "உங்கள் முழு உள்ளங்கையும் சட்டகத்தில் தெரிவதை உறுதிப்படுத்தவும்.",
        palmistryUploadButton: "சாதனத்திலிருந்து புகைப்படத்தைப் பதிவேற்றவும்",
        palmistryRetakeButton: "மீண்டும் எடுக்கவும்",
        palmistryAnalyzeButton: "உள்ளங்கையை பகுப்பாய்வு செய்யவும்",
        palmistryAnalyzingText: "விதியின் கோடுகளை பகுப்பாய்வு செய்கிறது...",
        consentTitle: "கைரேகை பகுப்பாய்வு ஒப்புதல்",
        consentBody1: "ஒரு கைரேகை வாசிப்பை வழங்க, நாங்கள் உங்கள் கையின் புகைப்படத்தை பகுப்பாய்வு செய்ய வேண்டும்.",
        consentBody2: "உங்கள் தனியுரிமை முக்கியமானது:",
        consentLi1: "உங்கள் புகைப்படம் இந்த ஒரு முறை வாசிப்பை உருவாக்குவதற்கு மட்டுமே பயன்படுத்தப்படுகிறது.",
        consentLi2: "படம் செயலாக்கப்படுகிறது மற்றும் அமர்வுக்குப் பிறகு எங்கள் சேவையகங்களில் சேமிக்கப்படாது.",
        consentLi3: "நாங்கள் உங்கள் புகைப்படத்தை வேறு எந்த நோக்கத்திற்காகவும் பயன்படுத்த மாட்டோம் அல்லது மூன்றாம் தரப்பினருடன் பகிர்ந்து கொள்ள மாட்டோம்.",
        consentBody3: "தொடர்வதன் மூலம், தனிப்பயனாக்கப்பட்ட கைரேகை வாசிப்பிற்காக உங்கள் உள்ளங்கைப் புகைப்படத்தை தற்காலிகமாக பதிவேற்றுவதற்கும் பகுப்பாய்வு செய்வதற்கும் நீங்கள் ஒப்புக்கொள்கிறீர்கள்.",
        consentDecline: "நிராகரிக்கவும்",
        consentAccept: "ஏற்றுக்கொண்டு தொடரவும்",
        footerText: "மேம்பட்ட ஜோதிட மாதிரிகளால் இயக்கப்படுகிறது. அனைத்து கணிப்புகளும் நிறுவப்பட்ட ஜோதிடக் கொள்கைகளை அடிப்படையாகக் கொண்டவை.",
    },
    te: {
        choosePathTitle: "జ్ఞానం కోసం మీ మార్గాన్ని ఎంచుకోండి",
        choosePathSubtitle: "మీ ఆవిష్కరణ ప్రయాణాన్ని ప్రారంభించడానికి ఒక పద్ధతిని ఎంచుకోండి.",
        formTitle: "మీ వివరాలను నమోదు చేయండి",
        formSubtitle: (techniqueName: string) => `ఖచ్చితమైన ${techniqueName} పఠనం కోసం మీ సమాచారాన్ని అందించండి.`,
        formNameLabel: "పూర్తి పేరు",
        formDobLabel: "పుట్టిన తేది",
        formTobLabel: "పుట్టిన సమయం",
        formPobLabel: "పుట్టిన ప్రదేశం (నగరం, దేశం)",
        formButton: "సంభాషణను ప్రారంభించండి",
        disclaimerTitle: "జ్యోతిష్య ఆధారం",
        disclaimerBody: "వైబ్ ఒరాకిల్ స్థాపించబడిన జ్యోతిష్య సూత్రాలు మరియు ప్రాచీన గ్రంథాలపై విస్తృతంగా శిక్షణ పొందిన AI నమూనాను ఉపయోగిస్తుంది. మా సిస్టమ్ మీ ప్రత్యేకమైన డేటా ఆధారంగా అంతర్దృష్టులను అందించడానికి గ్రహాల స్థానాలు మరియు విశ్వ అమరికలను వివరిస్తుంది.",
        disclaimerButton: "నా పఠనాన్ని ప్రారంభించండి",
        palmistryTitle: "మీ అరచేతి ఫోటోను అందించండి",
        palmistrySubtitle: "విశ్లేషణ కోసం మీ ఆధిపత్య చేతి యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి.",
        palmistryPreview: "మీ అరచేతి చిత్రం ఇక్కడ కనిపిస్తుంది.",
        palmistryInstructionsTitle: "స్పష్టమైన ఫోటో కోసం సూచనలు:",
        palmistryInstruction1: "మీ ఆధిపత్య చేతిని ఉపయోగించండి (మీరు వ్రాసేది).",
        palmistryInstruction2: "మంచి, సమానమైన లైటింగ్‌ను నిర్ధారించుకోండి. బలమైన నీడలను నివారించండి.",
        palmistryInstruction3: "మీ అరచేతిని ఫ్లాట్‌గా మరియు వేళ్లను కొద్దిగా వేరుగా ఉంచండి.",
        palmistryInstruction4: "మీ మొత్తం అరచేయి ఫ్రేమ్‌లో కనిపించేలా చూసుకోండి.",
        palmistryUploadButton: "పరికరం నుండి ఫోటోను అప్‌లోడ్ చేయండి",
        palmistryRetakeButton: "మళ్ళీ తీసుకోండి",
        palmistryAnalyzeButton: "అరచేతిని విశ్లేషించండి",
        palmistryAnalyzingText: "విధి రేఖలను విశ్లేషిస్తోంది...",
        consentTitle: "హస్తసాముద్రిక విశ్లేషణ సమ్మతి",
        consentBody1: "హస్తసాముద్రిక పఠనాన్ని అందించడానికి, మేము మీ చేతి ఫోటోను విశ్లేషించాలి.",
        consentBody2: "మీ గోప్యత ముఖ్యం:",
        consentLi1: "మీ ఫోటో ఈ ఒక్కసారి పఠనాన్ని రూపొందించడానికి మాత్రమే ఉపయోగించబడుతుంది.",
        consentLi2: "చిత్రం ప్రాసెస్ చేయబడుతుంది మరియు సెషన్ తర్వాత మా సర్వర్‌లలో నిల్వ చేయబడదు.",
        consentLi3: "మేము మీ ఫోటోను ఏ ఇతర ప్రయోజనం కోసం ఉపయోగించము లేదా మూడవ పార్టీలతో పంచుకోము.",
        consentBody3: "కొనసాగడం ద్వారా, వ్యక్తిగతీకరించిన హస్తసాముద్రిక పఠనం కోసం మీ అరచేతి ఫోటో యొక్క తాత్కాలిక అప్‌లోడ్ మరియు విశ్లేషణకు మీరు సమ్మతిస్తున్నారు.",
        consentDecline: "తిరస్కరించండి",
        consentAccept: "అంగీకరించి కొనసాగండి",
        footerText: "అధునాతన జ్యోతిష్య నమూనాల ద్వారా ఆధారితం. అన్ని అంచనాలు స్థాపించబడిన జ్యోతిష్య సూత్రాలపై ఆధారపడి ఉంటాయి.",
    },
    bn: {
        choosePathTitle: "আপনার অন্তর্দৃষ্টির পথ বেছে নিন",
        choosePathSubtitle: "আপনার আবিষ্কারের যাত্রা শুরু করতে একটি পদ্ধতি নির্বাচন করুন।",
        formTitle: "আপনার বিবরণ লিখুন",
        formSubtitle: (techniqueName: string) => `একটি সঠিক ${techniqueName} পড়ার জন্য আপনার তথ্য প্রদান করুন।`,
        formNameLabel: "পুরো নাম",
        formDobLabel: "জন্ম তারিখ",
        formTobLabel: "জন্ম সময়",
        formPobLabel: "জন্মস্থান (শহর, দেশ)",
        formButton: "কথোপকথন শুরু করুন",
        disclaimerTitle: "জ্যোতিষশাস্ত্রীয় ভিত্তি",
        disclaimerBody: "ভাইব ওরাকল প্রতিষ্ঠিত জ্যোতিষশাস্ত্রীয় নীতি এবং প্রাচীন ग्रंथগুলিতে ব্যাপকভাবে প্রশিক্ষিত একটি এআই মডেল ব্যবহার করে। আমাদের সিস্টেম আপনার অনন্য ডেটার উপর ভিত্তি করে অন্তর্দৃষ্টি প্রদান করতে গ্রহের অবস্থান এবং মহাজাগতিক সারিবদ্ধতা ব্যাখ্যা করে।",
        disclaimerButton: "আমার পড়া শুরু করুন",
        palmistryTitle: "আপনার করতলের ছবি দিন",
        palmistrySubtitle: "বিশ্লেষণের জন্য আপনার প্রভাবশালী হাতের একটি পরিষ্কার ছবি আপলোড করুন।",
        palmistryPreview: "আপনার করতলের ছবি এখানে দেখা যাবে।",
        palmistryInstructionsTitle: "পরিষ্কার ছবির জন্য নির্দেশাবলী:",
        palmistryInstruction1: "আপনার প্রভাবশালী হাত ব্যবহার করুন (যেটি দিয়ে আপনি লেখেন)।",
        palmistryInstruction2: "ভাল, সমান আলো নিশ্চিত করুন। শক্তিশালী ছায়া এড়িয়ে চলুন।",
        palmistryInstruction3: "আপনার করতল সমতল রাখুন এবং আঙ্গুলগুলি সামান্য আলাদা রাখুন।",
        palmistryInstruction4: "নিশ্চিত করুন যে আপনার পুরো করতল ফ্রেমে দৃশ্যমান।",
        palmistryUploadButton: "ডিভাইস থেকে ছবি আপলোড করুন",
        palmistryRetakeButton: "আবার তুলুন",
        palmistryAnalyzeButton: "করতল বিশ্লেষণ করুন",
        palmistryAnalyzingText: "ভাগ্যের রেখা বিশ্লেষণ করা হচ্ছে...",
        consentTitle: "হস্তরেখাবিদ্যা বিশ্লেষণ সম্মতি",
        consentBody1: "একটি হস্তরেখা পাঠ প্রদান করতে, আমাদের আপনার হাতের একটি ছবি বিশ্লেষণ করতে হবে।",
        consentBody2: "আপনার গোপনীয়তা গুরুত্বপূর্ণ:",
        consentLi1: "আপনার ছবি শুধুমাত্র এই এককালীন পাঠ তৈরি করার জন্য ব্যবহৃত হয়।",
        consentLi2: "ছবিটি প্রক্রিয়া করা হয় এবং অধিবেশনের পরে আমাদের সার্ভারে সংরক্ষণ করা হবে না।",
        consentLi3: "আমরা আপনার ছবি অন্য কোন উদ্দেশ্যে ব্যবহার করব না বা তৃতীয় পক্ষের সাথে শেয়ার করব না।",
        consentBody3: "এগিয়ে যাওয়ার মাধ্যমে, আপনি একটি ব্যক্তিগতকৃত হস্তরেখা পাঠের জন্য আপনার করতলের ছবির অস্থায়ী আপলোড এবং বিশ্লেষণে সম্মতি দিচ্ছেন।",
        consentDecline: "প্রত্যাখ্যান করুন",
        consentAccept: "গ্রহণ করুন এবং এগিয়ে যান",
        footerText: "উন্নত জ্যোতিষশাস্ত্রীয় মডেল দ্বারা চালিত। সমস্ত ভবিষ্যদ্বাণী প্রতিষ্ঠিত জ্যোতিষশাস্ত্রীয় নীতির উপর ভিত্তি করে।",
    },
    gu: {
        choosePathTitle: "તમારા અંતર્જ્ઞાનનો માર્ગ પસંદ કરો",
        choosePathSubtitle: "તમારી શોધની યાત્રા શરૂ કરવા માટે એક પદ્ધતિ પસંદ કરો.",
        formTitle: "તમારી વિગતો દાખલ કરો",
        formSubtitle: (techniqueName: string) => `ચોક્કસ ${techniqueName} વાંચન માટે તમારી માહિતી પ્રદાન કરો.`,
        formNameLabel: "પૂરું નામ",
        formDobLabel: "જન્મ તારીખ",
        formTobLabel: "જન્મ સમય",
        formPobLabel: "જન્મ સ્થળ (શહેર, દેશ)",
        formButton: "વાતચીત શરૂ કરો",
        disclaimerTitle: "જ્યોતિષીય આધાર",
        disclaimerBody: "વાઇબ ઓરેકલ સ્થાપિત જ્યોતિષીય સિદ્ધાંતો અને પ્રાચીન ગ્રંથો પર વ્યાપકપણે પ્રશિક્ષિત AI મોડેલનો ઉપયોગ કરે છે. અમારી સિસ્ટમ તમારા અનન્ય ડેટાના આધારે આંતરદૃષ્ટિ પ્રદાન કરવા માટે ગ્રહોની સ્થિતિ અને બ્રહ્માંડીય ગોઠવણીનું અર્થઘટન કરે છે.",
        disclaimerButton: "મારું વાંચન શરૂ કરો",
        palmistryTitle: "તમારા હથેળીનો ફોટો પ્રદાન કરો",
        palmistrySubtitle: "વિશ્લેષણ માટે તમારા પ્રભાવશાળી હાથનો સ્પષ્ટ ફોટો અપલોડ કરો.",
        palmistryPreview: "તમારી હથેળીની છબી અહીં દેખાશે.",
        palmistryInstructionsTitle: "સ્પષ્ટ ફોટો માટે સૂચનાઓ:",
        palmistryInstruction1: "તમારા પ્રભાવશાળી હાથનો ઉપયોગ કરો (જેનાથી તમે લખો છો).",
        palmistryInstruction2: "સારી, સમાન રોશનીની ખાતરી કરો. મજબૂત પડછાયાઓ ટાળો.",
        palmistryInstruction3: "તમારી હથેળીને સપાટ રાખો અને આંગળીઓને થોડી અલગ રાખો.",
        palmistryInstruction4: "ખાતરી કરો કે તમારી આખી હથેળી ફ્રેમમાં દેખાય છે.",
        palmistryUploadButton: "ઉપકરણમાંથી ફોટો અપલોડ કરો",
        palmistryRetakeButton: "ફરીથી લો",
        palmistryAnalyzeButton: "હથેળીનું વિશ્લેષણ કરો",
        palmistryAnalyzingText: "ભાગ્યની રેખાઓનું વિશ્લેષણ કરી રહ્યું છે...",
        consentTitle: "હસ્તરેખાશાસ્ત્ર વિશ્લેષણ સંમતિ",
        consentBody1: "હસ્તરેખા વાંચન પ્રદાન કરવા માટે, અમારે તમારા હાથના ફોટાનું વિશ્લેષણ કરવાની જરૂર છે.",
        consentBody2: "તમારી ગોપનીયતા મહત્વપૂર્ણ છે:",
        consentLi1: "તમારો ફોટો ફક્ત આ એક-વખતના વાંચન માટે જ વપરાય છે.",
        consentLi2: "છબી પર પ્રક્રિયા કરવામાં આવે છે અને સત્ર પછી અમારા સર્વર્સ પર સંગ્રહિત કરવામાં આવશે નહીં.",
        consentLi3: "અમે તમારા ફોટાનો ક્યારેય અન્ય કોઈ હેતુ માટે ઉપયોગ કરીશું નહીં અથવા તેને તૃતીય પક્ષો સાથે શેર કરીશું નહીં.",
        consentBody3: "આગળ વધીને, તમે વ્યક્તિગત હસ્તરેખા વાંચન માટે તમારા હથેળીના ફોટાના અસ્થાયી અપલોડ અને વિશ્લેષણ માટે સંમતિ આપો છો.",
        consentDecline: "નકારો",
        consentAccept: "સ્વીકારો અને આગળ વધો",
        footerText: "અદ્યતન જ્યોતિષીય મોડેલો દ્વારા સંચાલિત. બધી આગાહીઓ સ્થાપિત જ્યોતિષીય સિદ્ધાંતો પર આધારિત છે.",
    },
    kn: {
        choosePathTitle: "ನಿಮ್ಮ ಜ್ಞಾನದ ಹಾದಿಯನ್ನು ಆರಿಸಿ",
        choosePathSubtitle: "ನಿಮ್ಮ ಅನ್ವೇಷಣೆಯ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಲು ಒಂದು ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        formTitle: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
        formSubtitle: (techniqueName: string) => `ನಿಖರವಾದ ${techniqueName} ಓದುವಿಕೆಗಾಗಿ ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸಿ.`,
        formNameLabel: "ಪೂರ್ಣ ಹೆಸರು",
        formDobLabel: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
        formTobLabel: "ಹುಟ್ಟಿದ ಸಮಯ",
        formPobLabel: "ಹುಟ್ಟಿದ ಸ್ಥಳ (ನಗರ, ದೇಶ)",
        formButton: "ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        disclaimerTitle: "ಜ್ಯೋತಿಷ್ಯದ ಅಡಿಪಾಯ",
        disclaimerBody: "ವೈಬ್ ಒರಾಕಲ್ ಸ್ಥಾಪಿತ ಜ್ಯೋತಿಷ್ಯ ತತ್ವಗಳು ಮತ್ತು ಪ್ರಾಚೀನ ಗ್ರಂಥಗಳ ಮೇಲೆ ವ್ಯಾಪಕವಾಗಿ ತರಬೇತಿ ಪಡೆದ AI ಮಾದರಿಯನ್ನು ಬಳಸುತ್ತದೆ. ನಮ್ಮ ವ್ಯವಸ್ಥೆಯು ನಿಮ್ಮ ಅನನ್ಯ ಡೇಟಾದ ಆಧಾರದ ಮೇಲೆ ಒಳನೋಟಗಳನ್ನು ಒದಗಿಸಲು ಗ್ರಹಗಳ ಸ್ಥಾನಗಳು ಮತ್ತು ಬ್ರಹ್ಮಾಂಡದ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ.",
        disclaimerButton: "ನನ್ನ ಓದುವಿಕೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
        palmistryTitle: "ನಿಮ್ಮ ಅಂಗೈಯ ಫೋಟೋವನ್ನು ಒದಗಿಸಿ",
        palmistrySubtitle: "ವಿಶ್ಲೇಷಣೆಗಾಗಿ ನಿಮ್ಮ ಪ್ರಬಲ ಕೈಯ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        palmistryPreview: "ನಿಮ್ಮ ಅಂಗೈಯ ಚಿತ್ರ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
        palmistryInstructionsTitle: "ಸ್ಪಷ್ಟ ಫೋಟೋಕ್ಕಾಗಿ ಸೂಚನೆಗಳು:",
        palmistryInstruction1: "ನಿಮ್ಮ ಪ್ರಬಲ ಕೈಯನ್ನು ಬಳಸಿ (ನೀವು ಬರೆಯುವ ಕೈ).",
        palmistryInstruction2: "ಉತ್ತಮ, ಸಮನಾದ ಬೆಳಕನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ. ಬಲವಾದ ನೆರಳುಗಳನ್ನು ತಪ್ಪಿಸಿ.",
        palmistryInstruction3: "ನಿಮ್ಮ ಅಂಗೈಯನ್ನು ಚಪ್ಪಟೆಯಾಗಿ ಮತ್ತು ಬೆರಳುಗಳನ್ನು ಸ್ವಲ್ಪ ಅಂತರದಲ್ಲಿ ಇರಿಸಿ.",
        palmistryInstruction4: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಅಂಗೈ ಫ್ರೇಮ್‌ನಲ್ಲಿ ಗೋಚರಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
        palmistryUploadButton: "ಸಾಧನದಿಂದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        palmistryRetakeButton: "ಮತ್ತೆ ತೆಗೆದುಕೊಳ್ಳಿ",
        palmistryAnalyzeButton: "ಅಂಗೈಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
        palmistryAnalyzingText: "ಹಣೆಬರಹದ ರೇಖೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
        consentTitle: "ಹಸ್ತಸಾಮುದ್ರಿಕ ವಿಶ್ಲೇಷಣೆ ಒಪ್ಪಿಗೆ",
        consentBody1: "ಹಸ್ತಸಾಮುದ್ರಿಕ ಓದುವಿಕೆಯನ್ನು ಒದಗಿಸಲು, ನಾವು ನಿಮ್ಮ ಕೈಯ ಫೋಟೋವನ್ನು ವಿಶ್ಲೇಷಿಸಬೇಕಾಗಿದೆ.",
        consentBody2: "ನಿಮ್ಮ ಗೌಪ್ಯತೆ ಮುಖ್ಯ:",
        consentLi1: "ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಈ ಒಂದು ಬಾರಿಯ ಓದುವಿಕೆಗಾಗಿ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ.",
        consentLi2: "ಚಿತ್ರವನ್ನು ಸಂಸ್ಕರಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಅಧಿವೇಶನದ ನಂತರ ನಮ್ಮ ಸರ್ವರ್‌ಗಳಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ.",
        consentLi3: "ನಾವು ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಬೇರೆ ಯಾವುದೇ ಉದ್ದೇಶಕ್ಕಾಗಿ ಬಳಸುವುದಿಲ್ಲ ಅಥವಾ ಅದನ್ನು ಮೂರನೇ ವ್ಯಕ್ತಿಗಳೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.",
        consentBody3: "ಮುಂದುವರಿಯುವ ಮೂಲಕ, ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಹಸ್ತಸಾಮುದ್ರಿಕ ಓದುವಿಕೆಗಾಗಿ ನಿಮ್ಮ ಅಂಗೈಯ ಫೋಟೋದ ತಾತ್ಕಾಲಿಕ ಅಪ್‌ಲೋಡ್ ಮತ್ತು ವಿಶ್ಲೇಷಣೆಗೆ ನೀವು ಸಮ್ಮತಿಸುತ್ತೀರಿ.",
        consentDecline: "ನಿರಾಕರಿಸಿ",
        consentAccept: "ಒಪ್ಪಿಕೊಳ್ಳಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
        footerText: "ಮುಂದುವರಿದ ಜ್ಯೋತಿಷ್ಯ ಮಾದರಿಗಳಿಂದ ಚಾಲಿತವಾಗಿದೆ. ಎಲ್ಲಾ ಭವಿಷ್ಯವಾಣಿಗಳು ಸ್ಥಾಪಿತ ಜ್ಯೋತಿಷ್ಯ ತತ್ವಗಳನ್ನು ಆಧರಿಸಿವೆ.",
    },
    ml: {
        choosePathTitle: "നിങ്ങളുടെ ഉൾക്കാഴ്ചയിലേക്കുള്ള വഴി തിരഞ്ഞെടുക്കുക",
        choosePathSubtitle: "നിങ്ങളുടെ കണ്ടെത്തൽ യാത്ര ആരംഭിക്കുന്നതിന് ഒരു രീതി തിരഞ്ഞെടുക്കുക.",
        formTitle: "നിങ്ങളുടെ വിശദാംശങ്ങൾ നൽകുക",
        formSubtitle: (techniqueName: string) => `കൃത്യമായ ${techniqueName} വായനയ്ക്കായി നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക.`,
        formNameLabel: "മുഴുവൻ പേര്",
        formDobLabel: "ജനന തീയതി",
        formTobLabel: "ജനന സമയം",
        formPobLabel: "ജനന സ്ഥലം (നഗരം, രാജ്യം)",
        formButton: "സംഭാഷണം ആരംഭിക്കുക",
        disclaimerTitle: "ജ്യോതിഷപരമായ അടിസ്ഥാനം",
        disclaimerBody: "വൈബ് ഒറാക്കിൾ സ്ഥാപിതമായ ജ്യോതിഷ തത്വങ്ങളിലും പുരാതന ഗ്രന്ഥങ്ങളിലും വിപുലമായി പരിശീലനം ലഭിച്ച ഒരു എഐ മോഡൽ ഉപയോഗിക്കുന്നു. ഞങ്ങളുടെ സിസ്റ്റം നിങ്ങളുടെ തനതായ ഡാറ്റയെ അടിസ്ഥാനമാക്കി ഉൾക്കാഴ്ചകൾ നൽകുന്നതിന് ഗ്രഹങ്ങളുടെ സ്ഥാനങ്ങളും പ്രപഞ്ചത്തിന്റെ വിന്യാസങ്ങളും വ്യാഖ്യാനിക്കുന്നു.",
        disclaimerButton: "എന്റെ വായന ആരംഭിക്കുക",
        palmistryTitle: "നിങ്ങളുടെ കൈപ്പത്തിയുടെ ഫോട്ടോ നൽകുക",
        palmistrySubtitle: "വിശകലനത്തിനായി നിങ്ങളുടെ പ്രധാന കൈയുടെ വ്യക്തമായ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.",
        palmistryPreview: "നിങ്ങളുടെ കൈപ്പത്തിയുടെ ചിത്രം ഇവിടെ ദൃശ്യമാകും.",
        palmistryInstructionsTitle: "വ്യക്തമായ ഫോട്ടോയ്ക്കുള്ള നിർദ്ദേശങ്ങൾ:",
        palmistryInstruction1: "നിങ്ങളുടെ പ്രധാന കൈ ഉപയോഗിക്കുക (നിങ്ങൾ എഴുതുന്ന കൈ).",
        palmistryInstruction2: "നല്ല, തുല്യമായ വെളിച്ചം ഉറപ്പാക്കുക. ശക്തമായ നിഴലുകൾ ഒഴിവാക്കുക.",
        palmistryInstruction3: "നിങ്ങളുടെ കൈപ്പത്തി പരന്നതും വിരലുകൾ അല്പം അകലത്തിലുമായി വയ്ക്കുക.",
        palmistryInstruction4: "നിങ്ങളുടെ മുഴുവൻ കൈപ്പത്തിയും ഫ്രെയിമിൽ ദൃശ്യമാണെന്ന് ഉറപ്പാക്കുക.",
        palmistryUploadButton: "ഉപകരണത്തിൽ നിന്ന് ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
        palmistryRetakeButton: "വീണ്ടും എടുക്കുക",
        palmistryAnalyzeButton: "കൈപ്പത്തി വിശകലനം ചെയ്യുക",
        palmistryAnalyzingText: "വിധിയുടെ രേഖകൾ വിശകലനം ചെയ്യുന്നു...",
        consentTitle: "ഹസ്തരേഖാശാസ്ത്ര വിശകലനത്തിനുള്ള സമ്മതം",
        consentBody1: "ഒരു ഹസ്തരേഖാ വായന നൽകുന്നതിന്, നിങ്ങളുടെ കൈയുടെ ഒരു ഫോട്ടോ ഞങ്ങൾ വിശകലനം ചെയ്യേണ്ടതുണ്ട്.",
        consentBody2: "നിങ്ങളുടെ സ്വകാര്യത പ്രധാനമാണ്:",
        consentLi1: "നിങ്ങളുടെ ഫോട്ടോ ഈ ഒറ്റത്തവണ വായനയ്ക്കായി മാത്രമാണ് ഉപയോഗിക്കുന്നത്.",
        consentLi2: "ചിത്രം പ്രോസസ്സ് ചെയ്യുകയും സെഷനുശേഷം ഞങ്ങളുടെ സെർവറുകളിൽ സൂക്ഷിക്കുകയുമില്ല.",
        consentLi3: "ഞങ്ങൾ നിങ്ങളുടെ ഫോട്ടോ മറ്റ് ആവശ്യങ്ങൾക്കായി ഉപയോഗിക്കുകയോ മൂന്നാം കക്ഷികളുമായി പങ്കിടുകയോ ചെയ്യില്ല.",
        consentBody3: "മുന്നോട്ട് പോകുന്നതിലൂടെ, വ്യക്തിഗതമാക്കിയ ഹസ്തരേഖാ വായനയ്ക്കായി നിങ്ങളുടെ കൈപ്പത്തിയുടെ ഫോട്ടോ താൽക്കാലികമായി അപ്‌ലോഡ് ചെയ്യുന്നതിനും വിശകലനം ചെയ്യുന്നതിനും നിങ്ങൾ സമ്മതിക്കുന്നു.",
        consentDecline: "നിരസിക്കുക",
        consentAccept: "അംഗീകരിച്ച് തുടരുക",
        footerText: "വിപുലമായ ജ്യോതിഷ മോഡലുകളാൽ പ്രവർത്തിക്കുന്നു. എല്ലാ പ്രവചനങ്ങളും സ്ഥാപിതമായ ജ്യോതിഷ തത്വങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ളതാണ്.",
    },
    or: {
        choosePathTitle: "ଆପଣଙ୍କ ଅନ୍ତର୍ଦୃଷ୍ଟିର ପଥ ବାଛନ୍ତୁ",
        choosePathSubtitle: "ଆପଣଙ୍କର ଆବିଷ୍କାର ଯାତ୍ରା ଆରମ୍ଭ କରିବାକୁ ଏକ ପଦ୍ଧତି ବାଛନ୍ତୁ |",
        formTitle: "ଆପଣଙ୍କର ବିବରଣୀ ଦିଅନ୍ତୁ",
        formSubtitle: (techniqueName: string) => `ଏକ ସଠିକ୍ ${techniqueName} ପଠନ ପାଇଁ ଆପଣଙ୍କର ସୂଚନା ପ୍ରଦାନ କରନ୍ତୁ |`,
        formNameLabel: "ପୂରା ନାମ",
        formDobLabel: "ଜନ୍ମ ତାରିଖ",
        formTobLabel: "ଜନ୍ମ ସମୟ",
        formPobLabel: "ଜନ୍ମ ସ୍ଥାନ (ସହର, ଦେଶ)",
        formButton: "ଆଲୋଚନା ଆରମ୍ଭ କରନ୍ତୁ",
        disclaimerTitle: "ଜ୍ୟୋତିଷୀୟ ଆଧାର",
        disclaimerBody: "ଭାଇବ୍ ଓରାକଲ୍ ସ୍ଥାପିତ ଜ୍ୟୋତିଷୀୟ ସିଦ୍ଧାନ୍ତ ଏବଂ ପ୍ରାଚୀନ ଗ୍ରନ୍ଥଗୁଡ଼ିକ ଉପରେ ବ୍ୟାପକ ଭାବରେ ପ୍ରଶିକ୍ଷିତ ଏକ AI ମଡେଲ୍ ବ୍ୟବହାର କରେ | ଆମର ସିଷ୍ଟମ୍ ଆପଣଙ୍କର ଅନନ୍ୟ ଡାଟା ଉପରେ ଆଧାର କରି ଜ୍ଞାନ ପ୍ରଦାନ କରିବାକୁ ଗ୍ରହମାନଙ୍କର ସ୍ଥିତି ଏବଂ ବ୍ରହ୍ମାଣ୍ଡୀୟ ସମନ୍ୱୟକୁ ବ୍ୟାଖ୍ୟା କରେ |",
        disclaimerButton: "ମୋର ପଠନ ଆରମ୍ଭ କରନ୍ତୁ",
        palmistryTitle: "ଆପଣଙ୍କ ହାତର ଫଟୋ ଦିଅନ୍ତୁ",
        palmistrySubtitle: "ବିଶ୍ଳେଷଣ ପାଇଁ ଆପଣଙ୍କର ପ୍ରମୁଖ ହାତର ଏକ ସ୍ପଷ୍ଟ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ |",
        palmistryPreview: "ଆପଣଙ୍କ ହାତର ଛବି ଏଠାରେ ଦେଖାଯିବ |",
        palmistryInstructionsTitle: "ଏକ ସ୍ପଷ୍ଟ ଫଟୋ ପାଇଁ ନିର୍ଦ୍ଦେଶାବଳୀ:",
        palmistryInstruction1: "ଆପଣଙ୍କର ପ୍ରମୁଖ ହାତ ବ୍ୟବହାର କରନ୍ତୁ (ଯେଉଁଥିରେ ଆପଣ ଲେଖନ୍ତି) |",
        palmistryInstruction2: "ଭଲ, ସମାନ ଆଲୋକ ସୁନିଶ୍ଚିତ କରନ୍ତୁ | ଶକ୍ତିଶାଳୀ ଛାୟାକୁ ଏଡ଼ାନ୍ତୁ |",
        palmistryInstruction3: "ଆପଣଙ୍କ ହାତକୁ ସମତଳ ଏବଂ ଆଙ୍ଗୁଠିଗୁଡ଼ିକୁ ସାମାନ୍ୟ ଅଲଗା ରଖନ୍ତୁ |",
        palmistryInstruction4: "ସୁନିଶ୍ଚିତ କରନ୍ତୁ ଯେ ଆପଣଙ୍କର ସମଗ୍ର ହାତ ଫ୍ରେମରେ ଦୃଶ୍ୟମାନ ହେଉଛି |",
        palmistryUploadButton: "ଡିଭାଇସରୁ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ",
        palmistryRetakeButton: "ପୁଣି ଥରେ ନିଅନ୍ତୁ",
        palmistryAnalyzeButton: "ହାତକୁ ବିଶ୍ଳେଷଣ କରନ୍ତୁ",
        palmistryAnalyzingText: "ଭାଗ୍ୟର ରେଖାଗୁଡ଼ିକୁ ବିଶ୍ଳେଷଣ କରାଯାଉଛି...",
        consentTitle: "ହସ୍ତରେଖା ବିଜ୍ଞାନ ବିଶ୍ଳେଷଣ ସହମତି",
        consentBody1: "ଏକ ହସ୍ତରେଖା ପଠନ ପ୍ରଦାନ କରିବାକୁ, ଆମକୁ ଆପଣଙ୍କ ହାତର ଏକ ଫଟୋ ବିଶ୍ଳେଷଣ କରିବାକୁ ପଡିବ |",
        consentBody2: "ଆପଣଙ୍କର ଗୋପନୀୟତା ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ:",
        consentLi1: "ଆପଣଙ୍କର ଫଟୋ କେବଳ ଏହି ଏକକାଳୀନ ପଠନ ସୃଷ୍ଟି କରିବା ପାଇଁ ବ୍ୟବହୃତ ହୁଏ |",
        consentLi2: "ଛବିଟି ପ୍ରକ୍ରିୟାକୃତ ହୁଏ ଏବଂ ଅଧିବେଶନ ପରେ ଆମର ସର୍ଭରରେ ସଂରକ୍ଷିତ ହେବ ନାହିଁ |",
        consentLi3: "ଆମେ ଆପଣଙ୍କର ଫଟୋକୁ ଅନ୍ୟ କୌଣସି ଉଦ୍ଦେଶ୍ୟରେ ବ୍ୟବହାର କରିବୁ ନାହିଁ କିମ୍ବା ଏହାକୁ ତୃତୀୟ ପକ୍ଷଙ୍କ ସହିତ ସେୟାର କରିବୁ ନାହିଁ |",
        consentBody3: "ଆଗକୁ ବଢି, ଆପଣ ଏକ ବ୍ୟକ୍ତିଗତ ହସ୍ତରେଖା ପଠନ ପାଇଁ ଆପଣଙ୍କ ହାତର ଫଟୋର ଅସ୍ଥାୟୀ ଅପଲୋଡ୍ ଏବଂ ବିଶ୍ଳେଷଣ ପାଇଁ ସହମତି ଦିଅନ୍ତି |",
        consentDecline: "ଅଗ୍ରାହ୍ୟ କରନ୍ତୁ",
        consentAccept: "ଗ୍ରହଣ କରନ୍ତୁ ଏବଂ ଆଗକୁ ବଢନ୍ତୁ",
        footerText: "ଉନ୍ନତ ଜ୍ୟୋତିଷୀୟ ମଡେଲ ଦ୍ୱାରା ଚାଳିତ | ସମସ୍ତ ଭବିଷ୍ୟବାଣୀ ସ୍ଥାପିତ ଜ୍ୟୋତିଷୀୟ ସିଦ୍ଧାନ୍ତ ଉପରେ ଆଧାରିତ |",
    }
};
